version: '3'

services:
  collection:
    build: .
    ports:
      - "8001:80"
    volumes: 
      - ./datas/photos:/var/www/html/photos
      - ./datas/texts:/var/www/html/texts
  mysql:
    image: mysql:latest
    container_name: mysqlcollection
    volumes:
      - "./datas/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3308:3306"
    secrets:
      - db_password
secrets:
  db_password:
    file: ./db_password.txt